# Alternate original theme: "theme: jekyll-theme-tactile"
remote_theme: just-the-docs/just-the-docs
# remote_theme: pdmosses/just-the-docs@fix-external-links-without-pages

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

  # External navigation links
nav_external_links:
  - title: Return to the SRD Wiki
    url: https://srd.wiki
    hide_icon: false # set to true to hide the external link icon - defaults to false

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Aux links for the upper right navigation
aux_links:
  "View the GitHub Project":
    - "//github.com/OldManUmby/OSE.SRD.Wiki"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true
